import { PrismaClient } from '@prisma/client';
import bcrypt from 'bcryptjs';
import fs from 'fs';
import path from 'path';
const prisma = new PrismaClient();
const dir = path.join(__dirname, 'data');
function load<T>(file:string):T[]{const p=path.join(dir,file);return fs.existsSync(p)?JSON.parse(fs.readFileSync(p,'utf-8')):[]}
async function main(){
 const users=load<any>('users.json'),games=load<any>('games.json'),reviews=load<any>('reviews.json'),lists=load<any>('lists.json'),follows=load<any>('follows.json'),statuses=load<any>('status.json');
 for(const u of users){const existing=await prisma.tAB_USUARIO.findUnique({where:{nm_usuario:u.nm_usuario}});const senha=u.senha_usuario||(u.senha?await bcrypt.hash(u.senha,10):(existing?.senha_usuario||await bcrypt.hash('senha123',10)));await prisma.tAB_USUARIO.upsert({where:{nm_usuario:u.nm_usuario},update:{email_usuario:u.email_usuario,tipo_usuario:u.tipo_usuario,bio_usuario:u.bio_usuario,img_usuario:u.img_usuario},create:{nm_usuario:u.nm_usuario,email_usuario:u.email_usuario,senha_usuario:senha,tipo_usuario:u.tipo_usuario,bio_usuario:u.bio_usuario,img_usuario:u.img_usuario}})}
 for(const g of games){const admin=await prisma.tAB_USUARIO.findUnique({where:{nm_usuario:g.admin||'admin'}});await prisma.tAB_JOGOS.upsert({where:{nm_jogo:g.nm_jogo},update:{img_jogo:g.img_jogo,genero:g.genero,plataforma:g.plataforma,classificacao:g.classificacao,descricao:g.descricao,dt_jogo:new Date(g.dt_jogo)},create:{id_usuario:admin?.id_usuario,nm_jogo:g.nm_jogo,img_jogo:g.img_jogo,genero:g.genero,plataforma:g.plataforma,classificacao:g.classificacao,descricao:g.descricao,dt_jogo:new Date(g.dt_jogo)}})}
 for(const r of reviews){const u=await prisma.tAB_USUARIO.findUnique({where:{nm_usuario:r.usuario}});const j=await prisma.tAB_JOGOS.findUnique({where:{nm_jogo:r.jogo}});if(u&&j)await prisma.tAB_AVALIACAO.upsert({where:{id_usuario_id_jogo:{id_usuario:u.id_usuario,id_jogo:j.id_jogo}},update:{nota:r.nota,comentario:r.comentario,data_jogada:r.data_jogada?new Date(r.data_jogada):null},create:{id_usuario:u.id_usuario,id_jogo:j.id_jogo,nota:r.nota,comentario:r.comentario,data_jogada:r.data_jogada?new Date(r.data_jogada):null}})}
 for(const l of lists){const u=await prisma.tAB_USUARIO.findUnique({where:{nm_usuario:l.usuario}});if(!u)continue;let lista=await prisma.tAB_LISTA.findFirst({where:{id_usuario:u.id_usuario,nm_lista:l.nm_lista}});lista=lista?await prisma.tAB_LISTA.update({where:{id_lista:lista.id_lista},data:{descricao:l.descricao,publica:l.publica??true}}):await prisma.tAB_LISTA.create({data:{id_usuario:u.id_usuario,nm_lista:l.nm_lista,descricao:l.descricao,publica:l.publica??true}});for(const name of l.jogos||[]){const j=await prisma.tAB_JOGOS.findUnique({where:{nm_jogo:name}});if(j)await prisma.tAB_LISTA_JOGO.upsert({where:{id_lista_id_jogo:{id_lista:lista.id_lista,id_jogo:j.id_jogo}},update:{},create:{id_lista:lista.id_lista,id_jogo:j.id_jogo}})}}
 for(const f of follows){const a=await prisma.tAB_USUARIO.findUnique({where:{nm_usuario:f.seguidor}});const b=await prisma.tAB_USUARIO.findUnique({where:{nm_usuario:f.seguido}});if(a&&b&&a.id_usuario!==b.id_usuario)await prisma.tAB_FOLLOW.upsert({where:{id_usuario_seguidor_id_usuario_seguido:{id_usuario_seguidor:a.id_usuario,id_usuario_seguido:b.id_usuario}},update:{},create:{id_usuario_seguidor:a.id_usuario,id_usuario_seguido:b.id_usuario}})}
 for(const s of statuses){const u=await prisma.tAB_USUARIO.findUnique({where:{nm_usuario:s.usuario}});const j=await prisma.tAB_JOGOS.findUnique({where:{nm_jogo:s.jogo}});if(u&&j)await prisma.tAB_STATUS_JOGO.upsert({where:{id_usuario_id_jogo:{id_usuario:u.id_usuario,id_jogo:j.id_jogo}},update:{status:s.status,favorito:!!s.favorito,top_position:s.top_position},create:{id_usuario:u.id_usuario,id_jogo:j.id_jogo,status:s.status,favorito:!!s.favorito,top_position:s.top_position}})}
 console.log('Seed V1.2 Final concluído.');
}
main().catch(e=>{console.error(e);process.exit(1)}).finally(()=>prisma.$disconnect());
