import {Router} from 'express';import bcrypt from 'bcryptjs';import {z} from 'zod';import {prisma} from '../utils/prisma';import {generateToken} from '../utils/auth';import {authMiddleware,adminMiddleware,AuthRequest} from '../middlewares/auth.middleware';
export const routes=Router(); const safe=(u:any)=>{if(!u)return u;const{senha_usuario,...s}=u;return s}; const avg=(g:any)=>{const ns=g.avaliacoes?.map((a:any)=>a.nota)||[];const m=ns.length?ns.reduce((a:number,b:number)=>a+b,0)/ns.length:0;return{...g,media:Number(m.toFixed(1)),total_avaliacoes:ns.length}};
routes.get('/health',(req,res)=>res.json({status:'ok',app:'Checkpoint V1.2 Final'}));

routes.post('/auth/register',async(req,res)=>{const d=z.object({nm_usuario:z.string().min(3),email_usuario:z.string().email(),senha_usuario:z.string().min(6)}).parse(req.body);const exists=await prisma.tAB_USUARIO.findFirst({where:{OR:[{nm_usuario:d.nm_usuario},{email_usuario:d.email_usuario}]}});if(exists)return res.status(409).json({message:'Usuário ou e-mail já cadastrado.'});await prisma.tAB_USUARIO.create({data:{nm_usuario:d.nm_usuario,email_usuario:d.email_usuario,senha_usuario:await bcrypt.hash(d.senha_usuario,10),img_usuario:`https://api.dicebear.com/8.x/adventurer/svg?seed=${d.nm_usuario}`}});res.status(201).json({message:'Conta criada com sucesso. Faça login para continuar.'})});
routes.post('/auth/login',async(req,res)=>{const d=z.object({nm_usuario:z.string(),senha_usuario:z.string()}).parse(req.body);const u=await prisma.tAB_USUARIO.findUnique({where:{nm_usuario:d.nm_usuario}});if(!u||!(await bcrypt.compare(d.senha_usuario,u.senha_usuario)))return res.status(401).json({message:'Credenciais inválidas.'});const token=generateToken({id_usuario:u.id_usuario,nm_usuario:u.nm_usuario,tipo_usuario:u.tipo_usuario});res.json({user:safe(u),token})});
routes.get('/auth/me',authMiddleware,async(req:AuthRequest,res)=>res.json(safe(await prisma.tAB_USUARIO.findUnique({where:{id_usuario:req.usuario!.id_usuario},include:{_count:{select:{seguidores:true,seguindo:true,avaliacoes:true,listas:true}}}}))));

async function listGames(req:any,res:any){const {search='',genero='',ano='',classificacao='',take='60'}=req.query;const games=await prisma.tAB_JOGOS.findMany({where:{AND:[search?{nm_jogo:{contains:String(search)}}:{},genero?{genero:String(genero)}:{},classificacao?{classificacao:String(classificacao)}:{},ano?{dt_jogo:{gte:new Date(`${ano}-01-01`),lte:new Date(`${ano}-12-31`)}}:{}]},include:{avaliacoes:true},take:Number(take),orderBy:{nm_jogo:'asc'}});res.json(games.map(avg))}
routes.get(['/games','/jogos'],listGames);
routes.get(['/games/search','/jogos/search'],async(req,res)=>{const q=String(req.query.q||'').trim();if(q.length<2)return res.json([]);const games=await prisma.tAB_JOGOS.findMany({where:{nm_jogo:{contains:q}},include:{avaliacoes:true},take:6});res.json(games.map(avg).map((g:any)=>({id_jogo:g.id_jogo,nm_jogo:g.nm_jogo,img_jogo:g.img_jogo,genero:g.genero,media:g.media,total_avaliacoes:g.total_avaliacoes})))});
routes.get(['/games/:id','/jogos/:id'],async(req,res)=>{const g=await prisma.tAB_JOGOS.findUnique({where:{id_jogo:Number(req.params.id)},include:{avaliacoes:{include:{usuario:true},orderBy:{created_at:'desc'}},listas:{include:{lista:{include:{usuario:true}}}}}});if(!g)return res.status(404).json({message:'Jogo não encontrado'});res.json(avg({...g,avaliacoes:g.avaliacoes.map(a=>({...a,usuario:safe(a.usuario)}))}))});
const gameSchema=z.object({nm_jogo:z.string().min(2),img_jogo:z.string().url(),genero:z.string().optional().nullable(),plataforma:z.string().optional().nullable(),classificacao:z.string().optional().nullable(),descricao:z.string().optional().nullable(),dt_jogo:z.string()});
routes.post(['/games','/jogos'],authMiddleware,adminMiddleware,async(req:AuthRequest,res)=>{const d=gameSchema.parse(req.body);res.status(201).json(await prisma.tAB_JOGOS.create({data:{...d,id_usuario:req.usuario!.id_usuario,dt_jogo:new Date(d.dt_jogo)}}))});
routes.put(['/games/:id','/jogos/:id'],authMiddleware,adminMiddleware,async(req,res)=>{const d=gameSchema.partial().parse(req.body);const data:any={...d};if(d.dt_jogo)data.dt_jogo=new Date(d.dt_jogo);res.json(await prisma.tAB_JOGOS.update({where:{id_jogo:Number(req.params.id)},data}))});
routes.delete(['/games/:id','/jogos/:id'],authMiddleware,adminMiddleware,async(req,res)=>{await prisma.tAB_JOGOS.delete({where:{id_jogo:Number(req.params.id)}});res.json({message:'Jogo excluído.'})});

routes.get(['/reviews','/avaliacoes'],async(req,res)=>res.json((await prisma.tAB_AVALIACAO.findMany({include:{usuario:true,jogo:true},orderBy:{created_at:'desc'},take:40})).map(r=>({...r,usuario:safe(r.usuario)}))));
routes.post(['/reviews','/avaliacoes'],authMiddleware,async(req:AuthRequest,res)=>{const d=z.object({id_jogo:z.number(),nota:z.number().int().min(1).max(5),comentario:z.string().min(3).max(1000),data_jogada:z.string().optional().nullable()}).parse(req.body);res.status(201).json(await prisma.tAB_AVALIACAO.upsert({where:{id_usuario_id_jogo:{id_usuario:req.usuario!.id_usuario,id_jogo:d.id_jogo}},update:{nota:d.nota,comentario:d.comentario,data_jogada:d.data_jogada?new Date(d.data_jogada):null},create:{id_usuario:req.usuario!.id_usuario,id_jogo:d.id_jogo,nota:d.nota,comentario:d.comentario,data_jogada:d.data_jogada?new Date(d.data_jogada):null}}))});
routes.delete(['/reviews/:id','/avaliacoes/:id'],authMiddleware,async(req:AuthRequest,res)=>{const r=await prisma.tAB_AVALIACAO.findUnique({where:{id_avaliacao:Number(req.params.id)}});if(!r)return res.status(404).json({message:'Avaliação não encontrada.'});if(r.id_usuario!==req.usuario!.id_usuario&&req.usuario!.tipo_usuario!=='ADMIN')return res.status(403).json({message:'Sem permissão.'});await prisma.tAB_AVALIACAO.delete({where:{id_avaliacao:r.id_avaliacao}});res.json({message:'Avaliação excluída.'})});

async function listLists(req:any,res:any){const search=String(req.query.search||'').toLowerCase();const lists=await prisma.tAB_LISTA.findMany({where:{publica:true},include:{usuario:true,jogos:{include:{jogo:{include:{avaliacoes:true}}}}},orderBy:{created_at:'desc'}});res.json(search?lists.filter(l=>l.nm_lista.toLowerCase().includes(search)||String(l.descricao||'').toLowerCase().includes(search)||l.usuario.nm_usuario.toLowerCase().includes(search)):lists)}
routes.get(['/lists','/listas'],listLists);
routes.get(['/lists/user/:id_usuario','/listas/usuario/:id_usuario'],async(req,res)=>res.json(await prisma.tAB_LISTA.findMany({where:{id_usuario:Number(req.params.id_usuario)},include:{jogos:{include:{jogo:{include:{avaliacoes:true}}}}},orderBy:{created_at:'desc'}})));
routes.get(['/lists/:id','/listas/:id'],async(req,res)=>{const l=await prisma.tAB_LISTA.findUnique({where:{id_lista:Number(req.params.id)},include:{usuario:true,jogos:{include:{jogo:{include:{avaliacoes:true}}}}}});if(!l)return res.status(404).json({message:'Lista não encontrada.'});res.json(l)});
routes.post(['/lists','/listas'],authMiddleware,async(req:AuthRequest,res)=>{const d=z.object({nm_lista:z.string().min(2),descricao:z.string().optional().nullable(),publica:z.boolean().optional()}).parse(req.body);res.status(201).json(await prisma.tAB_LISTA.create({data:{id_usuario:req.usuario!.id_usuario,nm_lista:d.nm_lista,descricao:d.descricao,publica:d.publica??true}}))});
routes.post(['/lists/:id/games','/listas/:id/jogos'],authMiddleware,async(req,res)=>{await prisma.tAB_LISTA_JOGO.upsert({where:{id_lista_id_jogo:{id_lista:Number(req.params.id),id_jogo:Number(req.body.id_jogo)}},update:{},create:{id_lista:Number(req.params.id),id_jogo:Number(req.body.id_jogo)}});res.status(201).json({message:'Jogo adicionado.'})});
routes.delete(['/lists/:id/games/:id_jogo','/listas/:id/jogos/:id_jogo'],authMiddleware,async(req,res)=>{await prisma.tAB_LISTA_JOGO.deleteMany({where:{id_lista:Number(req.params.id),id_jogo:Number(req.params.id_jogo)}});res.json({message:'Jogo removido.'})});

routes.get(['/users','/usuarios'],authMiddleware,async(req,res)=>res.json((await prisma.tAB_USUARIO.findMany({include:{_count:{select:{seguidores:true,seguindo:true,avaliacoes:true,listas:true}}}})).map(safe)));
routes.get(['/users/:id','/usuarios/:id'],authMiddleware,async(req:AuthRequest,res)=>{const id=Number(req.params.id);const u=await prisma.tAB_USUARIO.findUnique({where:{id_usuario:id},include:{avaliacoes:{include:{jogo:true},orderBy:{created_at:'desc'}},listas:{include:{jogos:{include:{jogo:true}}}},status_jogos:{include:{jogo:{include:{avaliacoes:true}}},orderBy:{updated_at:'desc'}},_count:{select:{seguidores:true,seguindo:true,avaliacoes:true,listas:true}}}});if(!u)return res.status(404).json({message:'Usuário não encontrado'});const f=req.usuario!.id_usuario!==id?await prisma.tAB_FOLLOW.findUnique({where:{id_usuario_seguidor_id_usuario_seguido:{id_usuario_seguidor:req.usuario!.id_usuario,id_usuario_seguido:id}}}):null;res.json({...safe(u),isFollowing:!!f})});
routes.put(['/users/:id','/usuarios/:id'],authMiddleware,async(req:AuthRequest,res)=>{const id=Number(req.params.id);const isAdmin=req.usuario!.tipo_usuario==='ADMIN';if(req.usuario!.id_usuario!==id&&!isAdmin)return res.status(403).json({message:'Sem permissão'});const data:any={...req.body};if(data.senha_usuario)data.senha_usuario=await bcrypt.hash(data.senha_usuario,10);if(!isAdmin)delete data.tipo_usuario;res.json(safe(await prisma.tAB_USUARIO.update({where:{id_usuario:id},data}))) });
routes.post(['/users/:id/follow','/usuarios/:id/seguir'],authMiddleware,async(req:AuthRequest,res)=>{const target=Number(req.params.id);await prisma.tAB_FOLLOW.upsert({where:{id_usuario_seguidor_id_usuario_seguido:{id_usuario_seguidor:req.usuario!.id_usuario,id_usuario_seguido:target}},update:{},create:{id_usuario_seguidor:req.usuario!.id_usuario,id_usuario_seguido:target}});res.status(201).json({message:'Usuário seguido.'})});
routes.delete(['/users/:id/follow','/usuarios/:id/seguir'],authMiddleware,async(req:AuthRequest,res)=>{await prisma.tAB_FOLLOW.deleteMany({where:{id_usuario_seguidor:req.usuario!.id_usuario,id_usuario_seguido:Number(req.params.id)}});res.json({message:'Você deixou de seguir.'})});

routes.get(['/library','/biblioteca'],authMiddleware,async(req:AuthRequest,res)=>{const status=String(req.query.status||'TODOS');const where:any={id_usuario:req.usuario!.id_usuario};if(status&&status!=='TODOS'&&status!=='FAVORITOS'&&status!=='TOP4')where.status=status;if(status==='FAVORITOS')where.favorito=true;if(status==='TOP4')where.top_position={not:null};const items=await prisma.tAB_STATUS_JOGO.findMany({where,include:{jogo:{include:{avaliacoes:true}}},orderBy:[{top_position:'asc'},{updated_at:'desc'}]});res.json(items.map(i=>({...i,jogo:avg(i.jogo)}))) });
routes.post(['/library/games/:id/status','/biblioteca/jogos/:id/status'],authMiddleware,async(req:AuthRequest,res)=>{const d=z.object({status:z.enum(['QUERO_JOGAR','JOGANDO','ZERADO','ABANDONADO']).optional(),favorito:z.boolean().optional(),top_position:z.number().nullable().optional()}).parse(req.body);res.json(await prisma.tAB_STATUS_JOGO.upsert({where:{id_usuario_id_jogo:{id_usuario:req.usuario!.id_usuario,id_jogo:Number(req.params.id)}},update:d,create:{id_usuario:req.usuario!.id_usuario,id_jogo:Number(req.params.id),status:d.status||'QUERO_JOGAR',favorito:d.favorito??false,top_position:d.top_position}}))});
routes.post(['/library/games/:id/favorite','/biblioteca/jogos/:id/favorito'],authMiddleware,async(req:AuthRequest,res)=>{res.json(await prisma.tAB_STATUS_JOGO.upsert({where:{id_usuario_id_jogo:{id_usuario:req.usuario!.id_usuario,id_jogo:Number(req.params.id)}},update:{favorito:true},create:{id_usuario:req.usuario!.id_usuario,id_jogo:Number(req.params.id),favorito:true,status:'QUERO_JOGAR'}}))});
routes.delete(['/library/games/:id/favorite','/biblioteca/jogos/:id/favorito'],authMiddleware,async(req:AuthRequest,res)=>{await prisma.tAB_STATUS_JOGO.updateMany({where:{id_usuario:req.usuario!.id_usuario,id_jogo:Number(req.params.id)},data:{favorito:false,top_position:null}});res.json({message:'Favorito removido.'})});
routes.put(['/library/top-four','/biblioteca/top-four'],authMiddleware,async(req:AuthRequest,res)=>{const items=z.array(z.object({id_jogo:z.number(),position:z.number().min(1).max(4)})).max(4).parse(req.body.items||[]);await prisma.tAB_STATUS_JOGO.updateMany({where:{id_usuario:req.usuario!.id_usuario},data:{top_position:null}});for(const item of items){await prisma.tAB_STATUS_JOGO.upsert({where:{id_usuario_id_jogo:{id_usuario:req.usuario!.id_usuario,id_jogo:item.id_jogo}},update:{top_position:item.position,favorito:true},create:{id_usuario:req.usuario!.id_usuario,id_jogo:item.id_jogo,top_position:item.position,favorito:true,status:'QUERO_JOGAR'}})}res.json({message:'Top 4 atualizado.'})});

routes.get('/feed/discover',async(req,res)=>{const [reviews,lists,games]=await Promise.all([prisma.tAB_AVALIACAO.findMany({include:{usuario:true,jogo:true},orderBy:{created_at:'desc'},take:20}),prisma.tAB_LISTA.findMany({where:{publica:true},include:{usuario:true,jogos:{include:{jogo:true}}},orderBy:{created_at:'desc'},take:8}),prisma.tAB_JOGOS.findMany({include:{avaliacoes:true},orderBy:{created_at:'desc'},take:8})]);res.json({reviews:reviews.map(r=>({...r,usuario:safe(r.usuario)})),lists,games:games.map(avg)})});
routes.get('/feed/following',authMiddleware,async(req:AuthRequest,res)=>{const fs=await prisma.tAB_FOLLOW.findMany({where:{id_usuario_seguidor:req.usuario!.id_usuario}});const ids=fs.map(f=>f.id_usuario_seguido);const reviews=await prisma.tAB_AVALIACAO.findMany({where:{id_usuario:{in:ids.length?ids:[req.usuario!.id_usuario]}},include:{usuario:true,jogo:true},orderBy:{created_at:'desc'},take:30});res.json(reviews.map(r=>({...r,usuario:safe(r.usuario)}))) });
routes.get('/admin/dashboard',authMiddleware,adminMiddleware,async(req,res)=>{const [usuarios,jogos,avaliacoes,listas,status]=await Promise.all([prisma.tAB_USUARIO.count(),prisma.tAB_JOGOS.count(),prisma.tAB_AVALIACAO.count(),prisma.tAB_LISTA.count(),prisma.tAB_STATUS_JOGO.count()]);const av=await prisma.tAB_AVALIACAO.findMany();const mediaGeral=av.length?Number((av.reduce((a,b)=>a+b.nota,0)/av.length).toFixed(1)):0;res.json({totais:{usuarios,jogos,avaliacoes,listas,status,mediaGeral}})});
