import { Router } from 'express';
import bcrypt from 'bcryptjs';
import { z } from 'zod';
import { prisma } from '../utils/prisma';
import { generateToken } from '../utils/auth';
import { authMiddleware, adminMiddleware, AuthRequest } from '../middlewares/authMiddleware';
export const routes = Router();
const safe=(u:any)=>{if(!u)return u;const {senha_usuario,...rest}=u;return rest};
const gameInclude={avaliacoes:true} as any;
function avg(game:any){const notas=game.avaliacoes?.map((a:any)=>a.nota)||[];const media=notas.length?notas.reduce((a:number,b:number)=>a+b,0)/notas.length:0;return {...game,media:Number(media.toFixed(1)),total_avaliacoes:notas.length}}
routes.get('/health',(req,res)=>res.json({status:'ok',app:'Checkpoint V1.1'}));

routes.post('/auth/register',async(req,res)=>{const data=z.object({nm_usuario:z.string().min(3),email_usuario:z.string().email(),senha_usuario:z.string().min(6)}).parse(req.body);const exists=await prisma.tAB_USUARIO.findFirst({where:{OR:[{nm_usuario:data.nm_usuario},{email_usuario:data.email_usuario}]}});if(exists)return res.status(409).json({message:'Nome de usuário ou e-mail já cadastrado.'});await prisma.tAB_USUARIO.create({data:{nm_usuario:data.nm_usuario,email_usuario:data.email_usuario,senha_usuario:await bcrypt.hash(data.senha_usuario,10),img_usuario:`https://api.dicebear.com/8.x/adventurer/svg?seed=${data.nm_usuario}`}});return res.status(201).json({message:'Conta criada com sucesso. Faça login para continuar.'})});
routes.post('/auth/login',async(req,res)=>{const data=z.object({nm_usuario:z.string(),senha_usuario:z.string()}).parse(req.body);const user=await prisma.tAB_USUARIO.findUnique({where:{nm_usuario:data.nm_usuario}});if(!user||!(await bcrypt.compare(data.senha_usuario,user.senha_usuario)))return res.status(401).json({message:'Credenciais inválidas.'});const token=generateToken({id_usuario:user.id_usuario,nm_usuario:user.nm_usuario,tipo_usuario:user.tipo_usuario});res.json({user:safe(user),token})});
routes.get('/auth/me',authMiddleware,async(req:AuthRequest,res)=>{const user=await prisma.tAB_USUARIO.findUnique({where:{id_usuario:req.usuario!.id_usuario},include:{_count:{select:{seguidores:true,seguindo:true,avaliacoes:true,listas:true}}}});res.json(safe(user))});

routes.get('/home',async(req,res)=>{const [jogos,avaliacoes,listas]=await Promise.all([prisma.tAB_JOGOS.findMany({include:gameInclude,take:8,orderBy:{created_at:'desc'}}),prisma.tAB_AVALIACAO.findMany({include:{usuario:true,jogo:true},take:6,orderBy:{created_at:'desc'}}),prisma.tAB_LISTA.findMany({where:{publica:true},include:{usuario:true,jogos:{include:{jogo:true}}},take:4,orderBy:{created_at:'desc'}})]);res.json({jogos:jogos.map(avg),avaliacoes:avaliacoes.map(a=>({...a,usuario:safe(a.usuario)})),listas})});

routes.get('/jogos',async(req,res)=>{const {search='',genero='',ano='',classificacao=''}=req.query as any;const games=await prisma.tAB_JOGOS.findMany({where:{AND:[search?{nm_jogo:{contains:String(search)}}:{},genero?{genero:{contains:String(genero)}}:{},classificacao?{classificacao:String(classificacao)}:{},ano?{dt_jogo:{gte:new Date(`${ano}-01-01`),lte:new Date(`${ano}-12-31`)}}:{}]},include:gameInclude,orderBy:{nm_jogo:'asc'}});res.json(games.map(avg))});
routes.get('/jogos/:id',async(req:AuthRequest,res)=>{const id=Number(req.params.id);const game=await prisma.tAB_JOGOS.findUnique({where:{id_jogo:id},include:{avaliacoes:{include:{usuario:true},orderBy:{created_at:'desc'}}}});if(!game)return res.status(404).json({message:'Jogo não encontrado.'});res.json(avg({...game,avaliacoes:game.avaliacoes.map(a=>({...a,usuario:safe(a.usuario)}))}))});
const gameSchema=z.object({nm_jogo:z.string().min(2),img_jogo:z.string().url(),genero:z.string().optional().nullable(),plataforma:z.string().optional().nullable(),classificacao:z.string().optional().nullable(),descricao:z.string().optional().nullable(),dt_jogo:z.string()});
routes.post('/jogos',authMiddleware,adminMiddleware,async(req:AuthRequest,res)=>{const d=gameSchema.parse(req.body);const game=await prisma.tAB_JOGOS.create({data:{...d,id_usuario:req.usuario!.id_usuario,dt_jogo:new Date(d.dt_jogo)}});res.status(201).json(game)});
routes.put('/jogos/:id',authMiddleware,adminMiddleware,async(req,res)=>{const d=gameSchema.partial().parse(req.body);const data:any={...d};if(d.dt_jogo)data.dt_jogo=new Date(d.dt_jogo);res.json(await prisma.tAB_JOGOS.update({where:{id_jogo:Number(req.params.id)},data}))});
routes.delete('/jogos/:id',authMiddleware,adminMiddleware,async(req,res)=>{await prisma.tAB_JOGOS.delete({where:{id_jogo:Number(req.params.id)}});res.json({message:'Jogo excluído.'})});

routes.get('/avaliacoes',async(req,res)=>{const reviews=await prisma.tAB_AVALIACAO.findMany({include:{usuario:true,jogo:true},orderBy:{created_at:'desc'}});res.json(reviews.map(r=>({...r,usuario:safe(r.usuario)})))});
routes.post('/avaliacoes',authMiddleware,async(req:AuthRequest,res)=>{const d=z.object({id_jogo:z.number(),nota:z.number().int().min(1).max(5),comentario:z.string().min(3).max(1000),data_jogada:z.string().optional().nullable()}).parse(req.body);const review=await prisma.tAB_AVALIACAO.upsert({where:{id_usuario_id_jogo:{id_usuario:req.usuario!.id_usuario,id_jogo:d.id_jogo}},update:{nota:d.nota,comentario:d.comentario,data_jogada:d.data_jogada?new Date(d.data_jogada):null},create:{id_usuario:req.usuario!.id_usuario,id_jogo:d.id_jogo,nota:d.nota,comentario:d.comentario,data_jogada:d.data_jogada?new Date(d.data_jogada):null}});res.status(201).json(review)});
routes.delete('/avaliacoes/:id',authMiddleware,async(req:AuthRequest,res)=>{const review=await prisma.tAB_AVALIACAO.findUnique({where:{id_avaliacao:Number(req.params.id)}});if(!review)return res.status(404).json({message:'Avaliação não encontrada.'});if(review.id_usuario!==req.usuario!.id_usuario&&req.usuario!.tipo_usuario!=='ADMIN')return res.status(403).json({message:'Você só pode excluir suas avaliações.'});await prisma.tAB_AVALIACAO.delete({where:{id_avaliacao:review.id_avaliacao}});res.json({message:'Avaliação excluída.'})});

routes.get('/listas',async(req,res)=>res.json(await prisma.tAB_LISTA.findMany({where:{publica:true},include:{usuario:true,jogos:{include:{jogo:{include:gameInclude}}}},orderBy:{created_at:'desc'}})));
routes.get('/listas/usuario/:id_usuario',async(req,res)=>res.json(await prisma.tAB_LISTA.findMany({where:{id_usuario:Number(req.params.id_usuario)},include:{jogos:{include:{jogo:{include:gameInclude}}}},orderBy:{created_at:'desc'}})));
routes.get('/listas/:id',async(req,res)=>{const list=await prisma.tAB_LISTA.findUnique({where:{id_lista:Number(req.params.id)},include:{usuario:true,jogos:{include:{jogo:{include:gameInclude}}}}});if(!list)return res.status(404).json({message:'Lista não encontrada.'});res.json(list)});
routes.post('/listas',authMiddleware,async(req:AuthRequest,res)=>{const d=z.object({nm_lista:z.string().min(2),descricao:z.string().optional().nullable(),publica:z.boolean().optional()}).parse(req.body);res.status(201).json(await prisma.tAB_LISTA.create({data:{id_usuario:req.usuario!.id_usuario,nm_lista:d.nm_lista,descricao:d.descricao,publica:d.publica??true}}))});
routes.put('/listas/:id',authMiddleware,async(req:AuthRequest,res)=>{const list=await prisma.tAB_LISTA.findUnique({where:{id_lista:Number(req.params.id)}});if(!list)return res.status(404).json({message:'Lista não encontrada.'});if(list.id_usuario!==req.usuario!.id_usuario&&req.usuario!.tipo_usuario!=='ADMIN')return res.status(403).json({message:'Sem permissão.'});res.json(await prisma.tAB_LISTA.update({where:{id_lista:list.id_lista},data:req.body}))});
routes.delete('/listas/:id',authMiddleware,async(req:AuthRequest,res)=>{const list=await prisma.tAB_LISTA.findUnique({where:{id_lista:Number(req.params.id)}});if(!list)return res.status(404).json({message:'Lista não encontrada.'});if(list.id_usuario!==req.usuario!.id_usuario&&req.usuario!.tipo_usuario!=='ADMIN')return res.status(403).json({message:'Sem permissão.'});await prisma.tAB_LISTA.delete({where:{id_lista:list.id_lista}});res.json({message:'Lista excluída.'})});
routes.post('/listas/:id/jogos',authMiddleware,async(req,res)=>{const {id_jogo}=z.object({id_jogo:z.number()}).parse(req.body);await prisma.tAB_LISTA_JOGO.upsert({where:{id_lista_id_jogo:{id_lista:Number(req.params.id),id_jogo}},update:{},create:{id_lista:Number(req.params.id),id_jogo}});res.status(201).json({message:'Jogo adicionado.'})});
routes.delete('/listas/:id/jogos/:id_jogo',authMiddleware,async(req,res)=>{await prisma.tAB_LISTA_JOGO.deleteMany({where:{id_lista:Number(req.params.id),id_jogo:Number(req.params.id_jogo)}});res.json({message:'Jogo removido.'})});

routes.get('/usuarios',authMiddleware,async(req,res)=>res.json((await prisma.tAB_USUARIO.findMany({include:{_count:{select:{seguidores:true,seguindo:true,avaliacoes:true,listas:true}}},orderBy:{created_at:'desc'}})).map(safe)));
routes.get('/usuarios/:id',authMiddleware,async(req:AuthRequest,res)=>{const id=Number(req.params.id);const user=await prisma.tAB_USUARIO.findUnique({where:{id_usuario:id},include:{avaliacoes:{include:{jogo:true},orderBy:{created_at:'desc'}},listas:{include:{jogos:{include:{jogo:true}}},orderBy:{created_at:'desc'}},status_jogos:{include:{jogo:{include:gameInclude}},orderBy:{updated_at:'desc'}},_count:{select:{seguidores:true,seguindo:true,avaliacoes:true,listas:true}}}});if(!user)return res.status(404).json({message:'Usuário não encontrado.'});const follow=req.usuario!.id_usuario!==id?await prisma.tAB_FOLLOW.findUnique({where:{id_usuario_seguidor_id_usuario_seguido:{id_usuario_seguidor:req.usuario!.id_usuario,id_usuario_seguido:id}}}):null;res.json({...safe(user),isFollowing:Boolean(follow)})});
routes.put('/usuarios/:id',authMiddleware,async(req:AuthRequest,res)=>{const id=Number(req.params.id);const isAdmin=req.usuario!.tipo_usuario==='ADMIN';if(req.usuario!.id_usuario!==id&&!isAdmin)return res.status(403).json({message:'Sem permissão.'});const data:any={...req.body};if(data.senha_usuario)data.senha_usuario=await bcrypt.hash(data.senha_usuario,10);if(!isAdmin)delete data.tipo_usuario;res.json(safe(await prisma.tAB_USUARIO.update({where:{id_usuario:id},data}))) });
routes.delete('/usuarios/:id',authMiddleware,adminMiddleware,async(req:AuthRequest,res)=>{if(req.usuario!.id_usuario===Number(req.params.id))return res.status(400).json({message:'Não exclua sua própria conta.'});await prisma.tAB_USUARIO.delete({where:{id_usuario:Number(req.params.id)}});res.json({message:'Usuário excluído.'})});
routes.post('/usuarios/:id/seguir',authMiddleware,async(req:AuthRequest,res)=>{const target=Number(req.params.id);if(target===req.usuario!.id_usuario)return res.status(400).json({message:'Você não pode seguir a si mesmo.'});await prisma.tAB_FOLLOW.upsert({where:{id_usuario_seguidor_id_usuario_seguido:{id_usuario_seguidor:req.usuario!.id_usuario,id_usuario_seguido:target}},update:{},create:{id_usuario_seguidor:req.usuario!.id_usuario,id_usuario_seguido:target}});res.status(201).json({message:'Usuário seguido.'})});
routes.delete('/usuarios/:id/seguir',authMiddleware,async(req:AuthRequest,res)=>{await prisma.tAB_FOLLOW.deleteMany({where:{id_usuario_seguidor:req.usuario!.id_usuario,id_usuario_seguido:Number(req.params.id)}});res.json({message:'Você deixou de seguir este usuário.'})});

routes.get('/biblioteca',authMiddleware,async(req:AuthRequest,res)=>{const items=await prisma.tAB_STATUS_JOGO.findMany({where:{id_usuario:req.usuario!.id_usuario},include:{jogo:{include:gameInclude}},orderBy:{updated_at:'desc'}});res.json(items.map(i=>({...i,jogo:avg(i.jogo)})))});
routes.post('/jogos/:id/status',authMiddleware,async(req:AuthRequest,res)=>{const d=z.object({status:z.enum(['QUERO_JOGAR','JOGANDO','ZERADO','ABANDONADO']).optional(),favorito:z.boolean().optional(),top_position:z.number().nullable().optional()}).parse(req.body);const item=await prisma.tAB_STATUS_JOGO.upsert({where:{id_usuario_id_jogo:{id_usuario:req.usuario!.id_usuario,id_jogo:Number(req.params.id)}},update:d,create:{id_usuario:req.usuario!.id_usuario,id_jogo:Number(req.params.id),status:d.status||'QUERO_JOGAR',favorito:d.favorito??false,top_position:d.top_position}});res.json(item)});

routes.get('/feed/publico',async(req,res)=>{const reviews=await prisma.tAB_AVALIACAO.findMany({include:{usuario:true,jogo:true},orderBy:{created_at:'desc'},take:30});res.json(reviews.map(r=>({...r,usuario:safe(r.usuario),tipo:'AVALIACAO'})))});
routes.get('/feed/seguindo',authMiddleware,async(req:AuthRequest,res)=>{const follows=await prisma.tAB_FOLLOW.findMany({where:{id_usuario_seguidor:req.usuario!.id_usuario}});const ids=follows.map(f=>f.id_usuario_seguido);const reviews=await prisma.tAB_AVALIACAO.findMany({where:{id_usuario:{in:ids.length?ids:[req.usuario!.id_usuario]}},include:{usuario:true,jogo:true},orderBy:{created_at:'desc'},take:30});res.json(reviews.map(r=>({...r,usuario:safe(r.usuario),tipo:'AVALIACAO'})))});

routes.get('/admin/dashboard',authMiddleware,adminMiddleware,async(req,res)=>{const [usuarios,jogos,avaliacoes,listas,status]=await Promise.all([prisma.tAB_USUARIO.count(),prisma.tAB_JOGOS.count(),prisma.tAB_AVALIACAO.count(),prisma.tAB_LISTA.count(),prisma.tAB_STATUS_JOGO.count()]);const reviews=await prisma.tAB_AVALIACAO.findMany({include:{jogo:true,usuario:true}});const mediaGeral=reviews.length?Number((reviews.reduce((a,b)=>a+b.nota,0)/reviews.length).toFixed(1)):0;res.json({totais:{usuarios,jogos,avaliacoes,listas,status,mediaGeral}})});
